### ISSUE TITLE
'[BUG]' "Details"

### ISSUE THREAD

**Issue by AngryPotatoo** [chri3i/Ruvaak-Readme#13]
**Upload your crashlog**
Runs stable enough.

**Required: Modlist.txt**

You must also include your modlist.txt from `Ruvaak\profiles\Ruvaak`
[modlist - Copy.txt](https://github.com/chri3i/Ruvaak-Readme/files/9255700/modlist.-.Copy.txt)
Hope this works, just added the optional Quickloot RE mod. No other modifications were made to MCM besides the recommended settings.

**Describe the bug**
When leveling character stats such as Health Stamina and Magicka the stats dont increase past the base level 1 stats while skills advance. I can provide a youtube video of the issue

**To Reproduce**

2. Do '...'

**Expected behavior**
The numbers in the bottom left will momentarily increase but as soon as the stat menu is gone they revert back to normal.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug.

**Modlist version**

**Did you add any additional mods?**
Quickloot RE on nexus
***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
No just Quickloot RE was added

**Comment by chri3i** [comment]
'issue' is described [here](https://github.com/chri3i/Ruvaak-Readme/blob/main/changes%20to%20gameplay.md) in huge bold letters. it's a mod that does that and intentional.
