### ISSUE TITLE
'[BUG]' Can't Apply my Stat Points when leveling up no matter what I do.

### ISSUE THREAD

**Issue by Happyrama** [chri3i/Ruvaak-Readme#14]
[modlist.txt](https://github.com/chri3i/Ruvaak-Readme/files/9262663/modlist.txt)

Ok this may or may not be a bug but I simply cannot figure out how to apply my stat points when I level up, I have tried every button and button combination that I can think off and nothing seems to work, I have found the the PrintScreen key seems to work but it only applies one of the stats, that being light armor and nothing else no matter what I do whether that be be spammming it, holding it, pressing it on every other skill, It just doesn't work and quite frankly it is getting very annoying. If this is not a bug I apologize but cannot figure this out on my own and I need some help, Sorry once again.

1. Level up
2. Go to bed
3. Try to apply stats
4. Nothing works
5. Die

Well I expect to be able to level up and apply my stats

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug.

Version: Ruvaak 2.5.0.0

Yes I did add some mods, Mostly just small mods like Jobs of Skyrim, Unlimited Wood Chopping, Fashions of the Banditry, and some other mods like HDT, CBA Sliders and meshes, A mod that makes the posts in Riften more round and two more recent mods, Percision and S.C.A.R, However none of these things really should be affecting my leveling

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by chri3i** [comment]
you level through the stats menu. if the menu doesn't show up revert the list to the default state and try 8n a new game.
