### ISSUE TITLE
playing with controller there is no inventory access the b (or circle) button is unused why?'[BUG]' "Details"

### ISSUE THREAD

**Issue by RaSunTerran** [chri3i/Ruvaak-Readme#17]
**Upload your crashlog**

If you've crashed, upload your crashlog from `C:\Users\Username(unique to your PC)\Documents\My Games\Skyrim Special Edition\SKSE`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**

You must also include your modlist.txt from `Ruvaak\profiles\Ruvaak`

**Describe the bug**
A clear and concise description of what the bug is. Failure to do this will result in the report being **closed and ignored.**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug.

**Modlist version**

**Did you add any additional mods?**

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by chri3i** [comment]
read the readme
