### ISSUE TITLE
[REQUEST] Addition of Ice Titans

### ISSUE THREAD

**Issue by SyamOG** [chri3i/Ruvaak-Readme#7]
**What's the name of the mod and please provide a nexus link to it**
Ice Titans - Mihail Monsters and Animals. https://www.nexusmods.com/skyrimspecialedition/mods/47181?tab=description

**Why do you think that this mod would fit for Ruvaak?**
I believe this mod would be a great addition to the many horrifying monsters already found in Ruvaak. The way these giants look
also breathes new life into the game, as it looks like they may have scavenged the shipwrecks in the sea of ghosts for their gear.
I'd also like to include this short clip to further sell my point: https://www.youtube.com/watch?v=2YrUIWApNmI 

**Did you try the mod? How is the gameplay with it?**
I did not. From the videos I've watched I can say that they're extremely fast and hit quite hard.

**Did you try to add the mod to the list already?**
I did not.

**Comment by chri3i** [comment]
mod is hidden on nexus. naturally won't add it
