### ISSUE TITLE
Graphic bugs on the ground

### ISSUE THREAD

**Issue by azdrugr** [chri3i/Ruvaak-Readme#9]
I started out in Mor Khazgur, after leaving the camp, i saw weird texture bugs on the ground. I didnt moved up far from there, because i tried to "repair" it myself. After failing, i updated the modlist via wabbajack but nothing changed. I tried out another ENB Preset but this didnt changed it either. 
Screenshot
![uglyshit](https://user-images.githubusercontent.com/108432792/176538418-3f74a2d7-930e-4960-ac13-0f7848f7e520.PNG)

**To Reproduce**

1. Go to 'Outside of Mor Khazgur'
2. Do 'Walk'

**Modlist version**
Newest Wabbajack Version (cant read it because its white on white) EDIT: 2.3.0.0 according to MO2
![white on white](https://user-images.githubusercontent.com/108432792/176539371-804b1926-cb1c-4e45-b635-576593e883f5.PNG)

**Did you add any additional mods?**
Dead Man's Dread - Armoured and Temperable
Sithis Armour SE
Sithis Armour - Special Edition - Mastercraft
1DeadricArmorSE (disabled)
Armor of Intrigue

[modlist.txt](https://github.com/chri3i/Ruvaak-Readme/files/9014295/modlist.txt)

**Comment by chri3i** [comment]
most likely fixed in the upcoming version. It's from the grass mod afaik

**Comment by chri3i** [comment]
can confirm the fix now for sure
